git:
    submodules: false

sudo: required

language: ruby

services:
    - docker

script:
    # build all the tests
    - docker build -t decode-it/cook .

    # extract the cook binary
    - docker run --name cook decode-it/cook
    - docker cp cook:/var/cook/cook ./

    # and do some cleanup
    - docker run decode-it/cook /bin/bash -c "rm -rf /var/cook"


