language: cpp
os: 
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - rake
      - ninja-build

install:
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90

script: 
    - rake uth
    - rake b1:build
    - rake test
    - sudo -S rake install

