git:
    submodules: false

sudo: required

language: ruby

services:
    - docker

script:
    # build all the tests
    - docker build -t decode-it/cook .

    # extract the cook binary
    - docker run --name cook decode-it/cook
    - docker cp cook:/usr/bin/cook ./

before_deploy:
    # store the docker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker tag decode-it/cook thomasfannes/cook:latest
    - docker push thomasfannes/cook:latest

deploy:
    skip_cleanup: true
  - provider: script
    script: ls -lh cook
