language: cpp
os:
- linux
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - rake
    - ninja-build
install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
- rake uth
- rake b1:build
- rake test
deploy:
  provider: releases
  api_key:
    secure: xRJo9htbhYujfIO8M06L4w3EcreL50wnAxYlST+xa2io9t1bUubdXXCpDMDMP7gbvz98729iagUsMPAUkFuqV/t4Y5W8483mi2mCXASFUH+51aKC5N6PM1nU6vljrIoimPetaY1f9pWTAQYBcNzEc2+F2DzOL9yzAoaqvaaAGAgTRUleaSSYbKCdzBGLbASlgfhOZVW6I/YLtmAC1jklYHtqnHb84mb0zBmL9gh7IDca3BJbyeZIau/vr+PRFQdXXh8MtSGcabGp8bcyMHJzXnjm3/VWgcu1u/64oKz5w4stxGzcseb4T9uxe3ZRLzORB17Vy4QX6fkhfbM/t0WZ1m0KLCRq8rzJOly22R43A/mFoS1fHlSnUrJSKtJmj3M9jhYfFbQp3MrJIHqSvVrFQkxeyqmq1Dzvl7h9KZZmRmDsnWgvhJa8wC7euyHW11SAJqQYSqRAyQ9liNmQEjSi+sNRt1FMd7tC3WmuriIMSUHQ6Cgw7aLOKzTgQVRPX5Q/IRQFidovG3TNde2R759l3cLCNlZcFprwdPrTvimaZnkEBExbbUNd3EwPijZRuHgJh32JtsQFV7eNjlyYCgpgptbJcUQRC03TsF8mg7CzJJ/XMUbu8CHbV0NWUIuiYEJ8pEj2TSTeVTO+sJZBQwIKvRh14oTC09MgE9xi4iKP95w=
  file: cook.exe
  skip_cleanup: true
  on:
    repo: decode-it/cook
